/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation(project(":example:domain"))
    implementation(project(":example:infrastructure"))

    testImplementation(libs.assertj.core)
}

application {
    // Define the main class for the application.
    mainClass = "org.example.Application"
}
